"""
atlas.status — write STATUS.md from the cards, so it cannot drift.

    python run.py --status      rewrite STATUS.md
    python run.py --check       also refuses a STATUS.md that is out of date

STATUS.md used to be written by hand, and by 2026-09 it ran to 791 lines that
only a careful reader could tell apart from the plan. What a reader actually
needs from it is what exists today: which datasets the project makes, what each
one writes, who reads it, and which shells the whole thing is built from. All of
that is already declared in registry/, so it is rendered rather than retyped —
the same reason `meta.json` is generated from the source cards.

Everything else that was in STATUS — why a decision was made, what a source did
that cost a day — belongs to docs/, which this does not touch.
"""

from __future__ import annotations

from pathlib import Path

from atlas.core import registry as R

STATUS = R.ROOT / "STATUS.md"


def _size(path: Path) -> str:
    if not path.exists():
        return "—"
    kb = path.stat().st_size / 1000
    return f"{kb:,.0f} KB" if kb < 1000 else f"{kb / 1000:,.1f} MB"


def render() -> str:
    cards = R.datasets()
    groups = R.dataset_groups()
    steps = R.run_steps()
    shells = sorted(p.stem for p in (R.REGISTRY_DIR / "shells").glob("*.yaml"))
    sources = sorted(R.sources()["sources"])
    lines = [
        "# STATUS — what this project makes",
        "",
        "_Generated by `python run.py --status` from registry/. Do not edit by hand; `run.py --check` refuses a stale copy._",
        "",
        "The plan, and the only queue, is [`docs/PLAN.md`](docs/PLAN.md).",
        "Why things are the way they are is in `docs/`; this file is only what exists.",
        "",
        "## A full run",
        "",
        "```bash",
        "python run.py            # every step below, then verification",
        "python run.py --check    # every registry file against its schema",
        "```",
        "",
        "| Step | Runs |",
        "| --- | --- |",
    ]
    for number, step in sorted(steps.items()):
        lines.append(f"| {number} | `{step}` |")
    lines += ["", "## Datasets", ""]
    for group, members in groups.items():
        lines += [f"### {group}", "", "| Dataset | Writes | On the site | Read by |", "| --- | --- | --- | --- |"]
        for dataset in members:
            card = cards[dataset]
            outputs = "<br>".join(f"`{o}` ({_size(R.ROOT / o)})" for o in card["outputs"])
            readers = "<br>".join(f"`{c['path']}`" for c in card["consumed_by"])
            lines.append(f"| **{dataset}**<br>{card['title']} | {outputs} | {'yes' if card['on_screen'] else 'no'} | {readers} |")
        lines.append("")
    lines += [
        "## What they are built from",
        "",
        f"**{len(shells)} shells** (`registry/shells/`): " + ", ".join(f"`{s}`" for s in shells) + ".",
        "",
        f"**{len(sources)} sources** (`registry/sources/`): " + ", ".join(f"`{s}`" for s in sources) + ".",
        "",
        "Each shell card states its contract, invariants, refusals and the benchmark that proves it; each",
        "source card carries its licence, read and dated before its data was used.",
        "",
        "## What proves it still works",
        "",
        "```bash",
        "python run.py                                    # all of it, ending in a summary",
        "python run.py --test                             # the test suite, Python and web",
        "python run.py --verify                           # independent verification of the published files",
        "python verify/golden.py replay --name data-2026-09-21d  # the identity check",
        "python verify/golden.py live --manifest verify/golden/data-2026-09-21d/deployed.json \\",
        "    --url https://oscarsb2004.github.io/turkiye-economic-atlas   # what the published site serves",
        "```",
        "",
        "A golden master is one whole run, recorded: every download stored and the clock frozen, so any",
        "later revision can be run on exactly those inputs and its output compared byte for byte. The",
        "current one is `data-2026-09-21d`, and a master is recorded per data state. The site the published URL",
        "serves must also be the site this repository builds, which is what `golden.py live` checks.",
        "",
    ]
    return "\n".join(lines)


def write() -> bool:
    """Rewrite STATUS.md; True when it changed."""
    new = render()
    old = STATUS.read_text(encoding="utf-8") if STATUS.exists() else ""
    if new != old:
        STATUS.write_text(new, encoding="utf-8", newline="\n")
    return new != old


def is_current() -> bool:
    return STATUS.exists() and STATUS.read_text(encoding="utf-8") == render()
